version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongo_data:/data/db  

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - MONGO_URI=mongodb://mongodb:27017  
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - mongodb

  frontend:
    image: nginx:latest
    container_name: frontend
    ports:
      - "8081:80"  
    networks:
      - app-network
    volumes:
      - ./frontend:/usr/share/nginx/html  

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:  

